name:                haskell-kafka
version:             0.1.0.0
github:              "dabliuw22/haskell-kafka"
license:             BSD3
author:              "Will Leyton"
maintainer:          "wleylop22@gmail.com"
copyright:           "2020 Will Leyton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dabliuw22/haskell-kafka#readme>

dependencies:
  - base >= 4.5 && < 5
  - hw-kafka-client >= 3.1.2 && < 3.2
  - containers >= 0.6.2 && < 0.7
  - uuid >= 1.3.13 && < 1.4
  - text >= 1.2.2.1 && < 1.3
  - bytestring >= 0.10.10 && < 0.11
  - bytestring-conversion >= 0.1 && < 0.3.2
  - word8 >= 0.1.3 && < 0.2
  - time >= 1.9.3 && < 1.10
  - aeson <0.7.0.0 || > 0.7.0.0 && < 0.7.0.1 || > 0.7.0.1 && < 0.7.0.2 || > 0.7.0.2 && < 0.7.0.3 || > 0.7.0.3 && < 0.7.0.5 || > 0.7.0.5 && < 0.8.0.0 || > 0.8.0.0 && < 0.8.0.1 || > 0.8.0.1 && < 0.10.0.0 || > 0.10.0.0
  - hspec >=2.0 && < 3.0
  - QuickCheck < 2.11 || > 2.11 && < 2.11.1 || > 2.11.1 && < 2.11.2 || > 2.11.2 && < 2.12.6 || > 2.12.6 && < 2.13 || > 2.13
  - mtl >= 2.0.1 && < 2.3
  - transformers < 0.1.0.0 || > 0.1.0.0 && < 0.2.2.0 || > 0.2.2.0 && < 0.4.0.0 || > 0.4.0.0 && < 0.5.0.2 || > 0.5.0.2 && < 0.5.3.0 || > 0.5.3.0 && < 0.5.3.1 || > 0.5.3.1 && < 0.5.5.1 || > 0.5.5.1 && < 0.5.6.0 || > 0.5.6.0 && < 0.5.6.1 || > 0.5.6.1
  - lens >= 4.0 && < 4.20
  - katip >= 0.1.0.0 && < 0.8.6.0

library:
  source-dirs: src

executables:
  haskell-publisher-kafka-exe:
    main:                PublisherKafka.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is PublisherKafka
    dependencies:
    - haskell-kafka
  haskell-consumer-kafka-exe:
    main:                ConsumerKafka.hs
    source-dirs:         app
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is ConsumerKafka
    dependencies:
      - haskell-kafka

tests:
  haskell-kafka-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-kafka
